MvcBasic/MvcBasic/Models/Member.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcBasic.Models
{
    public class Member
    {
        [DisplayName("ID")]
        public int Id { get; set; }

        [DisplayName("氏名")]
        public string Name { get; set; }

        [DisplayName("メールアドレス")]
        public string Email { get; set; }

        [DisplayName("生年月日")]
        public DateTime Birth { get; set; }

        [DisplayName("既婚")]
        public bool Married { get; set; }

        [DisplayName("自己紹介")]
        public string Memo { get; set;}
    }
}

MvcBasic/MvcBasic/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcBasic.Models;

namespace MvcBasic.Controllers
{
    public class MembersController : Controller
    {
        private MvcBasicContext db = new MvcBasicContext();
        
        // GET: Members
        public ActionResult Index()
        {
            return View(db.Members.ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、http://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        // オーバーポスティング攻撃を防ぐためにBindを使っている
        public ActionResult Create([Bind(Include = "Id,Name,Email,Birth,Married,Memo")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、http://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,Birth,Married,Memo")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // Member member = db.Members.Find(id);
            // db.Members.Remove(member);
            // 下の2行か上の2行が必要
            var m = new Member() { Id = id };
            db.Entry(m).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();  // 接続を開放
            }
            base.Dispose(disposing);
        }

        public ActionResult Search(string name)
        {
            var articles = from member in db.Members select member;
            if (!string.IsNullOrEmpty(name))
            {
                articles = articles.Where(member => member.Name.Contains(name));
            }
            // OrderByは破壊的じゃない並び替え
            articles = articles.OrderByDescending(member => member.Id);

            // Distinct()：重複のないデータを取得する。破壊的じゃない。すべて一致していないと効果がない
            articles = articles.Distinct();
            return View(articles);
        }
    }
}

MvcBasic/MvcBasic/Views/Members/Create.cshtml
@model MvcBasic.Models.Member

@{
    ViewBag.Title = "Create";
}
@section scripts{
    <script>
        $(function () {
            $('h2').css('color', 'blue');
        });
    </script>
}

<h2>Create</h2>

@* この一行だけで十分 *@
@Html.Partial("_MemberPartial", Model)

MvcBasic/MvcBasic/Views/Members/Delete.cshtml
@model MvcBasic.Models.Member

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Married)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Married)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Memo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Memo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcBasic/MvcBasic/Views/Members/Details.cshtml
@model MvcBasic.Models.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Married)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Married)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Memo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Memo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcBasic/MvcBasic/Views/Members/Edit.cshtml
@model MvcBasic.Models.Member

@{
    ViewBag.Title = "Edit";
}
@section scripts{
    <script>
        $(function () {
            $('h2').css('color', '#ff00ff');
        });
    </script>
}
<h2>Edit</h2>
@* この一行だけで十分。Sharedの_MemberPartial.cshtmlを見てる *@
@{Html.RenderPartial("_MemberPartial", Model); }

MvcBasic/MvcBasic/Views/Members/Index.cshtml
@model IEnumerable<MvcBasic.Models.Member>
@{Layout = null;}
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Married)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Memo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Married)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Memo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
@Html.Action("CurrentTime", "Home")

MvcBasic/MvcBasic/Views/Members/Search.cshtml
@model IEnumerable<MvcBasic.Models.Member>
    @{ 
        ViewBag.Title = "Search";
    }
<h2>Search</h2>

@using (Html.BeginForm("Search", "Members", FormMethod.Get, new { @class = "form-inline" }))
{
    @Html.Label("Name","氏名：",new { @class = "control-label" })
    @Html.TextBox("Name", null, new { @class = "form-control" })
    <input type="submit" value="検索" class="btn btn-info"/>
}

<hr />
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>@Html.DisplayNameFor(model => model.Email)</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.Email)</td>
        </tr>
    }
</table>